# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "npm" # Specify your package ecosystem
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
      time: "02:00" # Time of day to check for updates
      timezone: "UTC" # Timezone for the time parameter
    open-pull-requests-limit: 5 # Limit the number of open PRs
    rebase-strategy: "auto" # Rebase strategy for the updates
    commit-message:
      prefix: "deps" # Prefix for commit messages
      include: "scope" # Include scope in commit messages
    ignore:
      - dependency-name: ".env" # Example to ignore specific packages
        versions: ["1.x"] # Example to ignore specific versions
